services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_MEMORY_LIMIT_MB=2048
    ports:
      - "1433:1433"
    networks:
      - orari-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  orari-app:
    build:
      context: .
      dockerfile: Orari/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=OrariDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true;ConnectRetryCount=5;ConnectRetryInterval=10
    networks:
      - orari-network

volumes:
  sqlserver_data:
    driver: local

networks:
  orari-network:
    driver: bridge
