// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orari.DataDbContext;

#nullable disable

namespace Orari.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250510223658_AddedDepartments")]
    partial class AddedDepartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orari.Models.Courses", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Orari.Models.Departments", b =>
                {
                    b.Property<int>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DId"));

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Orari.Models.Enrollments", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("SId")
                        .HasColumnType("int");

                    b.HasKey("EId");

                    b.HasIndex("CId");

                    b.HasIndex("SId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Orari.Models.Exams", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("CourseCId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorPId")
                        .HasColumnType("int");

                    b.Property<int>("RId")
                        .HasColumnType("int");

                    b.Property<int>("RoomRId")
                        .HasColumnType("int");

                    b.Property<int>("SCId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("EId");

                    b.HasIndex("CourseCId");

                    b.HasIndex("ProfesorPId");

                    b.HasIndex("RoomRId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Orari.Models.Profesors", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PId");

                    b.ToTable("Profesors");
                });

            modelBuilder.Entity("Orari.Models.Rooms", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RId"));

                    b.Property<int>("RCapacity")
                        .HasColumnType("int");

                    b.Property<string>("RDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Orari.Models.Schedules", b =>
                {
                    b.Property<int>("SCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SCId"));

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SCId");

                    b.HasIndex("EId")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Orari.Models.Students", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<DateTime>("SCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudyProgramsSPId")
                        .HasColumnType("int");

                    b.HasKey("SId");

                    b.HasIndex("StudyProgramsSPId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Orari.Models.StudyProgramCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("CourseCId")
                        .HasColumnType("int");

                    b.Property<int>("SPId")
                        .HasColumnType("int");

                    b.Property<int>("StudyProgramSPId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseCId");

                    b.HasIndex("StudyProgramSPId");

                    b.ToTable("StudyProgramCourses");
                });

            modelBuilder.Entity("Orari.Models.StudyPrograms", b =>
                {
                    b.Property<int>("SPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SPId"));

                    b.Property<int>("DId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentsDId")
                        .HasColumnType("int");

                    b.Property<string>("SPName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SPId");

                    b.HasIndex("DepartmentsDId");

                    b.ToTable("StudyPrograms");
                });

            modelBuilder.Entity("Orari.Models.Enrollments", b =>
                {
                    b.HasOne("Orari.Models.Courses", "Courses")
                        .WithMany("Enrollments")
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orari.Models.Students", "Students")
                        .WithMany("Enrollments")
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Orari.Models.Exams", b =>
                {
                    b.HasOne("Orari.Models.Courses", "Course")
                        .WithMany()
                        .HasForeignKey("CourseCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orari.Models.Profesors", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orari.Models.Rooms", "Room")
                        .WithMany()
                        .HasForeignKey("RoomRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Profesor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Orari.Models.Schedules", b =>
                {
                    b.HasOne("Orari.Models.Exams", "Exam")
                        .WithOne("Schedule")
                        .HasForeignKey("Orari.Models.Schedules", "EId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Orari.Models.Students", b =>
                {
                    b.HasOne("Orari.Models.StudyPrograms", null)
                        .WithMany("Students")
                        .HasForeignKey("StudyProgramsSPId");
                });

            modelBuilder.Entity("Orari.Models.StudyProgramCourse", b =>
                {
                    b.HasOne("Orari.Models.Courses", "Course")
                        .WithMany("StudyProgramCourse")
                        .HasForeignKey("CourseCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orari.Models.StudyPrograms", "StudyProgram")
                        .WithMany("StudyProgramCourse")
                        .HasForeignKey("StudyProgramSPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("Orari.Models.StudyPrograms", b =>
                {
                    b.HasOne("Orari.Models.Departments", "Departments")
                        .WithMany("StudyPrograms")
                        .HasForeignKey("DepartmentsDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Orari.Models.Courses", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudyProgramCourse");
                });

            modelBuilder.Entity("Orari.Models.Departments", b =>
                {
                    b.Navigation("StudyPrograms");
                });

            modelBuilder.Entity("Orari.Models.Exams", b =>
                {
                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("Orari.Models.Students", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Orari.Models.StudyPrograms", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("StudyProgramCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
