using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;

namespace Orari.Services
{
    public class PdfGenerateService : IPdfGenerateService
    {
        public byte[] GenerateSchedulePdf(string title, string content)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(x => x.FontSize(10));
                    page.Content().Element(BuildDocument);
                });
            });

            void BuildDocument(IContainer container)
            {
                container.Column(col =>
                {
                    // Header
                    col.Item().Element(HeaderSection);
                    
                    // Schedule Table
                    col.Item().PaddingTop(10).Element(c => ScheduleTableSection(c, content));
                    
                    // Footer
                    col.Item().PaddingTop(20).Element(FooterSection);
                });
            }

            void HeaderSection(IContainer container)
            {
                container.Column(col =>
                {
                    col.Item().AlignCenter().Text("ORARI - SCHEDULE SYSTEM").FontSize(16).Bold();
                    col.Item().AlignCenter().Text(title).FontSize(14).Bold();
                    col.Item().AlignCenter().Text($"Generated on: {DateTime.Now:dd/MM/yyyy HH:mm}").FontSize(10);
                });
            }

            void ScheduleTableSection(IContainer container, string content)
            {
                var scheduleData = ParseScheduleContent(content);
                
                if (scheduleData.Any())
                {
                    container.Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(1.2f); // Day
                            columns.RelativeColumn(1.5f); // Time
                            columns.RelativeColumn(2.5f); // Course
                            columns.RelativeColumn(1.8f); // Professor
                            columns.RelativeColumn(1.2f); // Room
                            columns.RelativeColumn(1.2f); // Year/Semester
                        });

                        // Header row
                        table.Header(header =>
                        {
                            header.Cell().Element(CellStyleHeader).Text("Day").Bold().FontSize(10);
                            header.Cell().Element(CellStyleHeader).Text("Time").Bold().FontSize(10);
                            header.Cell().Element(CellStyleHeader).Text("Course").Bold().FontSize(10);
                            header.Cell().Element(CellStyleHeader).Text("Professor").Bold().FontSize(10);
                            header.Cell().Element(CellStyleHeader).Text("Room").Bold().FontSize(10);
                            header.Cell().Element(CellStyleHeader).Text("Year/Semester").Bold().FontSize(10);
                        });

                        // Table content
                        foreach (var schedule in scheduleData)
                        {
                            table.Cell().Element(CellStyle).Text(schedule.Day).FontSize(9);
                            table.Cell().Element(CellStyle).Text(schedule.Time).FontSize(9);
                            table.Cell().Element(CellStyle).Text(schedule.Course).FontSize(9);
                            table.Cell().Element(CellStyle).Text(schedule.Professor).FontSize(9);
                            table.Cell().Element(CellStyle).Text(schedule.Room).FontSize(9);
                            table.Cell().Element(CellStyle).Text(schedule.YearSemester).FontSize(9);
                        }
                    });
                }
                else
                {
                    // Fallback to text if no structured data
                    container.Text(content).FontSize(12);
                }
            }

            void FooterSection(IContainer container)
            {
                container.Column(col =>
                {
                    col.Item().Text("Generated by Orari Schedule System").FontSize(9).AlignCenter();
                    col.Item().Text("University of Tirana - Faculty of Natural Sciences").FontSize(9).AlignCenter();
                    col.Item().Text("Department of Informatics").FontSize(9).AlignCenter();
                });
            }

            using (var ms = new MemoryStream())
            {
                document.GeneratePdf(ms);
                return ms.ToArray();
            }
        }

        private List<ScheduleRow> ParseScheduleContent(string content)
        {
            var scheduleData = new List<ScheduleRow>();
            var lines = content.Split('\n', StringSplitOptions.RemoveEmptyEntries);
            
            ScheduleRow currentRow = null;
            
            foreach (var line in lines)
            {
                var trimmedLine = line.Trim();
                
                if (trimmedLine.StartsWith("Day:") || trimmedLine.StartsWith("Date:"))
                {
                    if (currentRow != null)
                    {
                        scheduleData.Add(currentRow);
                    }
                    currentRow = new ScheduleRow();
                    currentRow.Day = ExtractValue(trimmedLine);
                }
                else if (trimmedLine.StartsWith("Time:"))
                {
                    if (currentRow != null)
                        currentRow.Time = ExtractValue(trimmedLine);
                }
                else if (trimmedLine.StartsWith("Course:"))
                {
                    if (currentRow != null)
                        currentRow.Course = ExtractValue(trimmedLine);
                }
                else if (trimmedLine.StartsWith("Professor:"))
                {
                    if (currentRow != null)
                        currentRow.Professor = ExtractValue(trimmedLine);
                }
                else if (trimmedLine.StartsWith("Room:"))
                {
                    if (currentRow != null)
                        currentRow.Room = ExtractValue(trimmedLine);
                }
                else if (trimmedLine.StartsWith("Semester:") || trimmedLine.StartsWith("Year:"))
                {
                    if (currentRow != null)
                        currentRow.YearSemester = ExtractValue(trimmedLine);
                }
                else if (trimmedLine.StartsWith("Study Program:"))
                {
                    if (currentRow != null)
                        currentRow.Course = $"{currentRow.Course} ({ExtractValue(trimmedLine)})";
                }
            }
            
            if (currentRow != null)
            {
                scheduleData.Add(currentRow);
            }
            
            return scheduleData;
        }

        private string ExtractValue(string line)
        {
            var colonIndex = line.IndexOf(':');
            if (colonIndex >= 0 && colonIndex < line.Length - 1)
            {
                return line.Substring(colonIndex + 1).Trim();
            }
            return string.Empty;
        }

        private IContainer CellStyle(IContainer container) =>
            container.Border(1).Padding(3).AlignCenter();
            
        private IContainer CellStyleHeader(IContainer container) =>
            container.Background(Colors.Grey.Lighten2).Border(1).Padding(3).AlignCenter();
    }

    public class ScheduleRow
    {
        public string Day { get; set; } = string.Empty;
        public string Time { get; set; } = string.Empty;
        public string Course { get; set; } = string.Empty;
        public string Professor { get; set; } = string.Empty;
        public string Room { get; set; } = string.Empty;
        public string YearSemester { get; set; } = string.Empty;
    }
} 